### ISSUE TITLE
Error with certain characters in password

### ISSUE THREAD

**Issue by NeffIsBack** [skelsec/aardwolf#11]
Hi, as shown in Porchetta-Industries/CrackMapExec#725 the RDPConnectionFactory throws an error if a password contains the symbol `#`. As you can see in the stacktrace from the issue, the method `urlparse`, used in commons->target.py line 68, uses the `#` character as seperator for "\<fragments\>", therefore not parsing the url correct and leading to not be able to return a port.

Here is a screenshot, that hopefully helps understanding the problem (this is output from the target.py `def from_url` function):

![image](https://user-images.githubusercontent.com/61382599/215610643-0d9e71b0-a8b9-4902-8065-5dedb6b87796.png)

**Comment by skelsec** [comment]
Yes, the URL format has this well-known problem with special characters, which can be easily mitigated by not using the URL format with string formatting. Looking at you @mpgn .
@NeffIsBack quick workaround could be to apply URLencoding to the password `password%23freswa` until the core issue is solved

**Comment by skelsec** [comment]
Actually, scrap that it won't work like that either :/
That part will need some improvements, in the meantime you can hex-encode the password and use `ntlm-pwhex` auth method.

**Comment by mpgn** [comment]
i will rewrite the code to use asyauth directly :)

**Comment by NeffIsBack** [comment]
Closing, as this code doesn’t exist anymore👍🏼
