### ISSUE TITLE
Error "cannot pickle 'Context' object"

### ISSUE THREAD

**Issue by ShallShell** [skelsec/aardwolf#12]
Hi all,
I am getting an error when running the following code based on the library:
**rdpurl = RDPConnectionFactory.from_url(url, iosettings)
conn = rdpurl.get_connection(iosettings)**

I am getting an error when the code is trying to do deepcopy "copy.deepcopy(iosettings)" - line 22 in "factory.py" file
"cannot pickle 'Context' object"

Can you assist, please

**Comment by skelsec** [comment]
Hello,
please show the full script, the command line and the full error output.  
It seems to be an error with the `iosettings` object parameters but I can't know that for sure until I see the script

**Comment by ShallShell** [comment]
Was taken from "connection.py"
```
async def amain():
    try:
        from aardwolf.commons.factory import RDPConnectionFactory
        from aardwolf.commons.iosettings import RDPIOSettings
        from aardwolf.extensions.RDPEDYC.channel import RDPEDYCChannel

        iosettings = RDPIOSettings()
        iosettings.channels.append(RDPEDYCChannel)
        url = 'rdp+ntlm-password://DER\Administrator:password@192.168.1.1'
        rdpurl = RDPConnectionFactory.from_url(url, iosettings)
        conn = rdpurl.get_connection(iosettings)
        _, err = await conn.connect()
        if err is not None:
            raise err

        while True:
            data = await conn.ext_out_queue.get()
        # print(data)
    except Exception as e:
        traceback.print_exc()


if __name__ == '__main__':
    asyncio.run(amain())
```

**Comment by skelsec** [comment]
it's strange, I've checked it now and it works for me (with the URL changed ofc)  
One thing I see in your code is that you use only one `\` in the URL parameter, it should look like
`'rdp+ntlm-password://DER\\Administrator:password@192.168.1.1'`  
Can you check with the correct number of `\` ?
What python version are you using?

**Comment by ShallShell** [comment]
Same mistake..
I am using Python 3.9.12

**Comment by skelsec** [comment]
Ahh! I can confirm there is a bug on `3.9`. It works on `3.10`, I will have to investigate.

**Comment by ShallShell** [comment]
Thank U for the update! waiting to hear from U

**Comment by skelsec** [comment]
I have updated the code and made a new release which should solve the issue, I tested it on all python versions from 3.7 to 3.11.
Can you verify it's working?

**Comment by ShallShell** [comment]
Now the error is not exists and the code is running! But getting an error when trying to connect - "_, err = await conn.connect()"
"CredSSP - Server sent an error! Code: 0xc000006d"
When in RDP configuration "Network level authentication" is disable (unchecked).

I am guessing this is something else but I am not sure.

**Comment by ShallShell** [comment]
Hi, any update about this?

**Comment by skelsec** [comment]
Please create a separate issue for this.  
So far I could not reproduce. Is the PW correct?
In the new issue please provide the URL you're using

**Comment by ShallShell** [comment]
Will do, thanks
