### ISSUE TITLE
Missing files in PyPI source distribution 

### ISSUE THREAD

**Issue by lesydimitri** [skelsec/aardwolf#13]
Installing the aardwolf source distribution through pip currently throws the following error:

```
error: can't find Rust extension project file: aardwolf/utils/rlers/Cargo.toml
[end of output]
  
note: This error originates from a subprocess, and is likely not a problem with pip.
```

I had a look in `aardwolf-0.2.6.tar.gz` and noticed the `rlers` directory only contains an `__init__.py` file.

The following list are files and directories that are present in the git repository but not in the .tar.gz:
```
aardwolf/develstuff/
aardwolf/develstuff/bitmaptest.py
aardwolf/develstuff/dectest.py
aardwolf/develstuff/pertest.py
aardwolf/develstuff/server_caps
aardwolf/develstuff/srvdata.py
aardwolf/develstuff/transporttest.py
aardwolf/protocol/T124/GCCPDU.asn
aardwolf/protocol/T125/MCSPDU.ver.2.asn
aardwolf/protocol/T125/MCSPDU.ver.3.asn
aardwolf/protocol/pdu/capabilities/.gitignore
aardwolf/utils/rectconvert.bak
aardwolf/utils/ducky/dtest.txt
aardwolf/utils/ducky/dtest2.txt
aardwolf/utils/ducky/dtest3.txt
aardwolf/utils/rlers/Cargo.lock
aardwolf/utils/rlers/Cargo.toml
aardwolf/utils/rlers/pyproject.toml
aardwolf/utils/rlers/src/
aardwolf/utils/rlers/src/rle.rs
builder/
builder/manylinux/
builder/manylinux/build.sh
builder/pyinstaller/
builder/pyinstaller/build.bat
builder/windows/
builder/windows/build.bat
```

**Comment by skelsec** [comment]
Thank you for the list! I'll fix this in the next release!

**Comment by qu35t-code** [comment]
Hey @skelsec,

Thanks for your job !
I have the same error when installing the latest crackmapexec update.
Do you think the fix will be done quickly or is it better to downgrade to an older version ?

**Comment by skelsec** [comment]
hello all,
I created a [new release](https://github.com/skelsec/aardwolf/releases/tag/0.2.7) which should fix this issue.  
the same version is also on pyp. I tested the source dist by building the project on a raspberry pi.  
Please verify and close if all good!

**Comment by qu35t-code** [comment]
Hey @skelsec,

Thanks very much, it works fine !
You can close this issue !

**Comment by lesydimitri** [comment]
> hello all,
> I created a [new release](https://github.com/skelsec/aardwolf/releases/tag/0.2.7) which should fix this issue.
> the same version is also on pyp. I tested the source dist by building the project on a raspberry pi.
> Please verify and close if all good!

Works flawlessly, I just successfully installed version 0.2.7 in both macOS 13.2.1 and EndeavourOS (ARM) using pip.
Thank you for investing your time into fixing this!
