### ISSUE TITLE
Missing source distribution

### ISSUE THREAD

**Issue by lesydimitri** [skelsec/aardwolf#2]
Hi! 

I noticed the package for this project on PyPI is missing a source distribution.
This caused the installation to fail on my ARM64 based machine, since no built distribution is available for that architecture.

Cloning the repository and building it manually worked like a charm, so adding a source distribution might make the installation a bit more comfortable for people using uncommon architectures.

**Comment by skelsec** [comment]
Hello! Thank you for the issue!
I knew this problem was ought to come up sooner or later, however I don't know how to do that exactly.
When packaging the project to upload to pyp I get an error for the source distribution. This is why I tried to pack it in the current way.  
Can you give a hint on how to do source distribution?

**Comment by lesydimitri** [comment]
Exactly what command is throwing an error for you? Already when you package it using `python3 setup.py sdist`?
For me that does everything as expected and a **.tar.gz** file ends up in the **dist** folder.

I'm not that experienced with the packaging process myself, but it seems that a lot of people are relying on [Twine](https://twine.readthedocs.io/en/stable/) to make the upload process easier.

[This website](https://python-packaging-tutorial.readthedocs.io/en/latest/uploading_pypi.html) seems to outline the process pretty well.

**Comment by skelsec** [comment]
okay, I found the "issue", source distribution is now on pyp!
Please close this issue if you consider it fixed

**Comment by lesydimitri** [comment]
Confirmed working :-) Thanks a lot!
