### ISSUE TITLE
Async runtime error

### ISSUE THREAD

**Issue by XiaoliChan** [skelsec/aardwolf#20]
Will get the async runtime error, not sure what happened
![image](https://github.com/skelsec/aardwolf/assets/30458572/ae84c682-959f-486b-aee0-7ffcf3597107)

**Comment by jborean93** [comment]
This is a CPython error, make sure you are running on the latest 3.11 or 3.12 release and it should fix this problem https://github.com/python/cpython/issues/109538.

**Comment by XiaoliChan** [comment]
@jborean93 Thanks for your solution, The issue is close!
