### ISSUE TITLE
pypi: broken 0.2.9 source tar.gz file

### ISSUE THREAD

**Issue by blshkv** [skelsec/aardwolf#29]
https://pypi.org/project/aardwolf/
[aardwolf-0.2.9.tar.gz ](https://files.pythonhosted.org/packages/2d/26/829a42d7803d21a272c6a1fb9ca5163945dd8e4adfb92660365746e582b3/aardwolf-0.2.9.tar.gz)(44.4 kB)

The file is too small and missing all python and may be other source code

**Comment by blshkv** [comment]
also, setup.py must be broken, as ```python setup.py install --prefix /tmp/aardwolf``` does not install python packages.

```
bash$ find *
bin
bin/ardpscan
lib
lib/python3.12
lib/python3.12/site-packages
lib/python3.12/site-packages/librlers.cpython-312-x86_64-linux-gnu.so
lib/python3.12/site-packages/aardwolf-0.2.9-py3.12.egg-info
lib/python3.12/site-packages/aardwolf-0.2.9-py3.12.egg-info/top_level.txt
lib/python3.12/site-packages/aardwolf-0.2.9-py3.12.egg-info/dependency_links.txt
lib/python3.12/site-packages/aardwolf-0.2.9-py3.12.egg-info/requires.txt
lib/python3.12/site-packages/aardwolf-0.2.9-py3.12.egg-info/entry_points.txt
lib/python3.12/site-packages/aardwolf-0.2.9-py3.12.egg-info/SOURCES.txt
lib/python3.12/site-packages/aardwolf-0.2.9-py3.12.egg-info/not-zip-safe
lib/python3.12/site-packages/aardwolf-0.2.9-py3.12.egg-info/PKG-INFO
```

ardpscan fails to start with the following error:
```
ModuleNotFoundError: No module named 'aardwolf'
```

**Comment by skelsec** [comment]
This was indeed the case, but there has been 2 other versions since, I just forgot to tag this on github. can you please check the deployment via pip on version `0.2.11` ?

**Comment by blshkv** [comment]
seems fine. Thank you
