### ISSUE TITLE
Missing License information

### ISSUE THREAD

**Issue by sbrun** [skelsec/aardwolf#4]
Hello,

There is no license information. Can you add a file LICENSE.txt or at least mention the license in the setup.py? 
We would like to package this module for Kali Linux and we need to know the license.

Thanks

**Comment by skelsec** [comment]
Hello, there was an issue with a piece of C code I relied on for the framebuffer decompression which would've made the code licensed under GPL (probably?) which I wanted to avoid. Now, after rewriting/using different codebase for the same functionality I can release this under MIT.
I also added the LICENSE file now, so all should be well!

**Comment by sbrun** [comment]
Hello
Thank you very much. I will package the module for Kali.
